export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL"
export const STU_INFO="STU_INFO"
export const STU_TRANSCRIPT="STU_TRANSCRIPT"
export const STU_PAYMENTS="STU_PAYMENTS"
export const STU_REQUEST="STU_REQUEST"
export const STU_COMPLAINTS="STU_COMPLAINTS"